# .github/workflows/python-app.yml
name: Python Titanic CI

on:
  push:
    branches: [hippo]
  pull_request:
    branches: [hippo]

jobs:
  test:
    runs-on: ubuntu-22.04 

    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
            echo "DATA_DIR=./data" >> $GITHUB_ENV
            echo "MODELS_DIR=./models" >> $GITHUB_ENV

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      - name: Run tests with coverage
        run: |
          pytest --cov=titanic --cov-report=xml

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
            name: coverage-report-python-${{ matrix.python-version }}
            path: coverage.xml
